### ISSUE TITLE
Request Network ACL Rules number support

### ISSUE THREAD

**Issue by MRinalducci** [xanzy/terraform-provider-cloudstack#31] opened 2018-03-09 15:51 UTC
Hi,

After reviewing the code of [resource_cloudstack_network_acl_rule.go](https://github.com/terraform-providers/terraform-provider-cloudstack/blob/master/cloudstack/resource_cloudstack_network_acl_rule.go)
it seems not possible to specify a "rule number" parameter for ordering them.

This is a important feature in firewalling when you need that rules are ordered.

Moreover the function `SetNumber` exists in the cloudstack client [NetworkACLService.go](https://github.com/xanzy/go-cloudstack/blob/master/cloudstack/NetworkACLService.go).

This issue is to ask the support of an additionnal parameter to specify a rule number in a rule as it is supported in Cloudstack.

Thank you for reviewing this issue.

**Comment by svanharmelen** [comment] 2018-03-09 19:58
@MRinalducci the rules are ordered. That is, they are applied in the order that you defined them in your Terraform config.

But your point is still valid and it should be pretty straightforward to add support for the `number` parameter. I will try to find some time for it next week...

**Comment by MRinalducci** [comment] 2018-03-09 21:30
@svanharmelen thanks for your quick reply!

> @MRinalducci the rules are ordered. That is, they are applied in the order that you defined them in your Terraform config.

Yes, this is true for the first creation, but not when you update them (as I tested).
For example, initially you define 3 rules in your Terraform code:

- Rule 1
- Rule 2
- Rule 3

Then you want to insert a new rule between 1 and 2 in your TF code:

- Rule 1
- Rule 4
- Rule 2
- Rule 3

Because rule 1, 2 and 3 are already existing in the ACL, it will add Rule 4 at the end of the ACL like that:

- Rule 1
- Rule 2
- Rule 3
- Rule 4

Which is not reflecting the TF code in term of order.

> But your point is still valid and it should be pretty straightforward to add support for the number parameter. I will try to find some time for it next week...

Yes, I think so, as I could see. This will be great, thank you very much for that!
Let me know if I could do anything for helping.

**Comment by svanharmelen** [comment] 2018-03-09 21:38
Interesting observation! Thanks for the details 👍🏻

**Comment by svanharmelen** [comment] 2018-03-12 10:58
@MRinalducci it turns out this is a little more complicated then I initially expected.

The problem is that the `cloudstack_network_acl_rule` resource allows you to specify a list of ports in a single `rule` block, where CloudStack only allows one port (or port range) per rule. So the resource is actually able to generate (and keep track of) multiple rules generated for a single `rule` block in the config.

This makes it virtually impossible to assign rule numbers in the `rule` blocks. Changing the code to support it would mean introducing breaking changes and changing the (currently expected) behaviour of this resource.

So I see a couple of possible solutions. We could enrich the resource by a `number` and a `port` parameter and then add restriction so you can either use the `ports` parameters, or the `port` and `number` parameters. But not both in one and the same resource.

Another solution (which I think I prefer) would be to fix the ordering issue you described, so it will always match the order in your Terraform config.

What do you think?

**Comment by MRinalducci** [comment] 2018-03-12 13:01
@svanharmelen that's right, I didn't saw that problem at first look.

> Another solution (which I think I prefer) would be to fix the ordering issue you described, so it will always match the order in your Terraform config.

Yes, this would be nicest solution of both (I think too). This will also avoid to always put a rule number. But, we have to be aware to keep the right order also when we declare 2 or more `cloudstack_network_acl_rule` resources.
I mean the ordered rules declared in the second resource have to be placed after the ordered rules of first resource. I think this will work right away.

**Comment by greut** [comment] 2018-03-12 13:28
`cidrlist` has the same kind of behaviour than `ports` I guess.

**Comment by svanharmelen** [comment] 2018-03-12 14:09
I’m going to look into that option then @MRinalducci.

And CloudStack does accept CIDR lists @greut, so it’s only for `ports`.

**Comment by greut** [comment] 2018-03-12 14:11
@svanharmelen doesn't it create many rules from the `cidrlist`, like it does for the ingress/egress rules.

**Comment by MRinalducci** [comment] 2018-03-12 16:00
@svanharmelen I think we have also to be aware of argument `parallelism (Optional) Specifies how much rules will be created or deleted concurrently. (defaults 2)` which can sometimes change the ordering (to be confirmed).

**Comment by svanharmelen** [comment] 2018-03-12 16:17
@MRinalducci yeah, good one... Will take that into account. Didn't have time to continue on this today, but will have another look tomorrow.

**Comment by svanharmelen** [comment] 2018-03-12 16:21
@greut no, it doesn't: https://github.com/terraform-providers/terraform-provider-cloudstack/blob/master/cloudstack/resource_cloudstack_network_acl_rule.go#L188-L193

**Comment by MRinalducci** [comment] 2018-03-29 09:01
Hello @svanharmelen, any update about this issue?

**Comment by svanharmelen** [comment] 2018-03-29 10:55
@MRinalducci, yes... I don't have much dedicated time to work on this, so I try to look at it in lost moments here and there :wink: It turns out to be a little more complex then you would expect, but I think I'm close to a solution. Will keep you posted!

**Comment by MRinalducci** [comment] 2018-03-29 11:36
@svanharmelen thank you very much for your update and your work on this issue. Yes, as discussed it is more complex than expected, but it's great that you're near a solution! :+1:

**Comment by MRinalducci** [comment] 2018-04-24 16:47
Thanks for the update :)

**Comment by MRinalducci** [comment] 2018-08-28 14:53
@svanharmelen any update about this issue? :)

**Comment by svanharmelen** [comment] 2018-08-28 20:04
Yes and no... There is still an open tab in my browser and the wish to fix it, but without direct access to a running CloudStack API it's a bit harder to work on this then before.

I'll see what I can do to get some API access and take it from there...

**Comment by MRinalducci** [comment] 2018-08-29 08:13
Oh I see the problem...
I hope you can get some API access soon for testing.
Thanks for the input!

**Comment by svanharmelen** [comment] 2021-07-26 11:54
I'm going to close this issue as I'm about to archive this repository. Development of this provider has been moved to the Apache Foundation. Please find the new home for this provider here: https://github.com/apache/cloudstack-terraform-provider

**Closed by svanharmelen** 2021-07-26 11:54 UTC
Labels: enhancement
